config:
  showdiff: true
  import_configs:
    - config.yaml.d/dotfiles/shell.yaml
    - config.yaml.d/dotfiles/vim.yaml
    - config.yaml.d/dotfiles/git.yaml
    - config.yaml.d/dotfiles/tmux.yaml
    - config.yaml.d/dotfiles/ssh.yaml
    - config.yaml.d/transformations/gpg.yaml
dotfiles: {}
profiles:
  base:
    variables:
      work: false
      laptop: false
    dynvariables:
      uname: "uname -s | tr '[:upper:]' '[:lower:]'"
    include:
      - shell
      - git
      - ssh
      - vim
      - tmux
  base.work:
    variables:
      work: true
    include:
      - shell.work
      - git.work
      - ssh.work
  janeway:
    variables:
      laptop: true
    include:
      - base
  nuc:
    include:
      - base
  lcars:
    include:
      - base
  zordon.local:
    variables:
      laptop: true
    include:
      - base
      - base.work
