actions:
  post:
    tmux_reload: env | grep -q TMUX && tmux source-file ~/.tmux.conf
    tpm_install_plugins: TMUX_PLUGIN_MANAGER_PATH=~/.tmux/plugins ~/.tmux/plugins/tpm/bin/install_plugins
  pre:
    tpm_install: test -e ~/.tmux/plugins/tpm || (mkdir -p ~/.tmux/plugins && git clone
      https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm)
    vim-dirs: (mkdir -p ~/.vim/.backup ~/.vim/.swp ~/.vim/.undo)
  vim-plug: vim +PlugInstall +qall
config:
  showdiff: true
dotfiles:
  00_bash_login:
    dst: ~/.bash_login
    src: shell/bash_login
  01_bashrc:
    dst: ~/.bashrc
    src: shell/bashrc
  02_gitconfig:
    dst: ~/.gitconfig
    src: git/gitconfig
  03_id_rsa:
    dst: ~/.ssh/id_rsa
    src: ssh/id_rsa
    trans_read: gpg_ssh
  04_id_rsa.pub:
    dst: ~/.ssh/id_rsa.pub
    src: ssh/id_rsa.pub
  05_plug.vim:
    dst: ~/.vim/autoload/plug.vim
    src: vim/autoload/plug.vim
  06_vimrc:
    actions:
    - vim-plug
    - vim-dirs
    dst: ~/.vimrc
    src: vim/vimrc
  07_tmux.conf:
    actions:
    - tpm_install
    - tpm_install_plugins
    - tmux_reload
    dst: ~/.tmux.conf
    src: tmux/tmux.conf
  08_bash_aliases:
    dst: ~/.bash_aliases
    src: shell/bash_aliases
  09_ssh_config:
    dst: ~/.ssh/config
    src: ssh/config
  10_bash_aliases.work:
    dst: ~/.bash_aliases.work
    src: shell/bash_aliases.work
    trans_read: gpg
  11_ssh_config.work:
    dst: ~/.ssh/config.work
    src: ssh/config.work
    trans_read: gpg
  12_gitconfig_Work:
    dst: ~/.gitconfig-work
    src: git/gitconfig-work
  13_ssh_authorized_keys:
    dst: ~/.ssh/authorized_keys
    src: ssh/authorized_keys
profiles:
  janeway:
    dotfiles: []
    include:
    - linux
    - linux_server
  linux:
    dotfiles:
    - 07_tmux.conf
  linux_server:
    dotfiles:
    - 00_bash_login
    - 01_bashrc
    - 02_gitconfig
    - 03_id_rsa
    - 04_id_rsa.pub
    - 05_plug.vim
    - 06_vimrc
    - 08_bash_aliases
    - 09_ssh_config
    - 13_ssh_authorized_keys
  mac_work:
    dotfiles:
    - ALL
  nuc:
    dotfiles: []
    include:
    - linux
    - linux_server
  lcars:
    dotfiles: []
    include:
    - linux
    - linux_server
  pi-games:
    dotfiles: []
    include:
    - linux_server
  zordon.local:
    dotfiles: []
    include:
    - mac_work
trans_read:
  gpg: gpg -q -d {0} > {1}
  gpg_ssh: gpg -q -d {0} > {1} && chmod 0600 {1}
