config:
  showdiff: true
  import_configs:
    - config.yaml.d/dotfiles/asdf.yaml
    - config.yaml.d/dotfiles/bash.yaml
    - config.yaml.d/dotfiles/zsh.yaml
    - config.yaml.d/dotfiles/vim.yaml
    - config.yaml.d/dotfiles/git.yaml
    - config.yaml.d/dotfiles/tmux.yaml
    - config.yaml.d/dotfiles/ssh.yaml
    - config.yaml.d/dotfiles/starship.yaml
    - config.yaml.d/dotfiles/alacritty.yaml
    - config.yaml.d/dotfiles/gpg.yaml
    - config.yaml.d/transformations/gpg.yaml
dotfiles: {}
profiles:
  ## Meta
  base:
    variables:
      mac: false
      laptop: false
      homebrew_prefix: /opt/homebrew
    dynvariables:
      uname: "uname -s | tr '[:upper:]' '[:lower:]'"
    include:
      - asdf
      - bash
      - zsh
      - git
      - ssh
      - starship
      - vim
      - tmux
      - gpg
      - alacritty
      # - nvim

  ## Machines
  janeway.local:
    variables:
      laptop: true
      mac: true
    include:
      - base
  chakotay.local:
    variables:
      laptop: true
      mac: true
    include:
      - base
  sisko.local:
    variables:
      laptop: true
      mac: true
    include:
      - base
  tuvok.local:
    variables:
      laptop: true
      mac: true
    include:
      - base

  codespaces:
    variables:
      mac: false
      laptop: false
    include:
      - bash
      - zsh
      - git
      - starship
