config:
  showdiff: true
  import_configs:
    - config.yaml.d/dotfiles/shell.yaml
    - config.yaml.d/dotfiles/vim.yaml
    - config.yaml.d/dotfiles/git.yaml
    - config.yaml.d/dotfiles/tmux.yaml
    - config.yaml.d/dotfiles/ssh.yaml
    - config.yaml.d/transformations/gpg.yaml
dotfiles: {}
profiles:
  janeway:
    dotfiles: []
    include:
    - linux
    - linux_server
  linux:
    dotfiles:
    - tmux.conf
  linux_server:
    dotfiles:
    - bash_login
    - bashrc
    - gitconfig
    - id_rsa
    - id_rsa.pub
    - autoload_vimplug
    - vimrc
    - bash_aliases
    - ssh_config
    - ssh_authorized_keys
  mac_work:
    dotfiles:
    - ALL
  nuc:
    dotfiles: []
    include:
    - linux
    - linux_server
  lcars:
    dotfiles: []
    include:
    - linux
    - linux_server
  pi-games:
    dotfiles: []
    include:
    - linux_server
  zordon.local:
    dotfiles: []
    include:
    - mac_work
