config:
  showdiff: true
  import_configs:
    - config.yaml.d/dotfiles/bash.yaml
    - config.yaml.d/dotfiles/zsh.yaml
    - config.yaml.d/dotfiles/vim.yaml
    - config.yaml.d/dotfiles/git.yaml
    - config.yaml.d/dotfiles/tmux.yaml
    - config.yaml.d/dotfiles/ssh.yaml
    - config.yaml.d/dotfiles/starship.yaml
    - config.yaml.d/dotfiles/terminal.yaml
    - config.yaml.d/dotfiles/gpg.yaml
    - config.yaml.d/transformations/gpg.yaml
dotfiles: {}
profiles:
  ## Meta
  base:
    variables:
      mac: false
      work: false
      laptop: false
    dynvariables:
      uname: "uname -s | tr '[:upper:]' '[:lower:]'"
    include:
      - bash
      - zsh
      - git
      - ssh
      - starship
      - vim
      - nvim
      - tmux
      - gpg
      - alacritty
  base.work:
    variables:
      work: true
    # include: []

  ## Machines
  janeway.local:
    variables:
      laptop: true
      mac: true
    include:
      - base
  chakotay.local:
    variables:
      laptop: true
      mac: true
    include:
      - base
      - base.work

  codespaces:
    variables:
      mac: false
      work: false
      laptop: false
    include:
      - bash
      - zsh
      - git
      - starship
