config:
  showdiff: true
  import_configs:
    - config.yaml.d/dotfiles/bash.yaml
    - config.yaml.d/dotfiles/zsh.yaml
    - config.yaml.d/dotfiles/vim.yaml
    - config.yaml.d/dotfiles/git.yaml
    - config.yaml.d/dotfiles/tmux.yaml
    - config.yaml.d/dotfiles/ssh.yaml
    - config.yaml.d/dotfiles/terminal.yaml
    - config.yaml.d/dotfiles/gpg.yaml
    - config.yaml.d/transformations/gpg.yaml
dotfiles: {}
profiles:
  ## Meta
  base:
    variables:
      mac: false
      work: false
      laptop: false
    dynvariables:
      uname: "uname -s | tr '[:upper:]' '[:lower:]'"
    include:
      - bash
      - zsh
      - git
      - ssh
      - vim
      - tmux
      - gpg
  base.work:
    variables:
      work: true
    include:
      - bash.work
      - zsh.work
      - git.work
      - ssh.work

  ## Machines
  janeway:
    variables:
      laptop: true
    include:
      - base
      - alacritty
      - base.work
  nuc:
    include:
      - base
  lcars:
    include:
      - base
      - terminfo-xterm-256color
  zordon.local:
    variables:
      laptop: true
      mac: true
    include:
      - base
      - base.work
      - alacritty
