[directory]
truncation_length = 30
style = "bold blue"

[aws]
disabled = true

[gcloud]
disabled = true

# I think this is a bug, "default" context is showing...
[docker_context]
disabled = true

[shell]
disabled = false

{%@@ if work @@%}
[kubernetes]
disabled = false
{%@@ endif @@%}
