typeset -U path
[[ -d ~/bin ]] && path=(~/bin $path)

{%@@ if mac @@%}
postgres_bin=/Applications/Postgres.app/Contents/Versions/latest/bin
[[ -d $postgres_bin ]] && path=($postgres_bin $path)
{%@@ endif @@%}

export GOPATH=~/projects/go

[[ -d ~/.zsh/fpath ]] && fpath=($fpath ~/.zsh/fpath)
