typeset -U path
[[ -d ~/bin ]] && path=(~/bin $path)
[[ -d ~/.poetry/bin ]] && path=(~/.poetry/bin $path)

{%@@ if mac @@%}
postgres_bin=/Applications/Postgres.app/Contents/Versions/latest/bin
[[ -d $postgres_bin ]] && path=($postgres_bin $path)
{%@@ endif @@%}

[[ -d /usr/local/go/bin ]] && path=(/usr/local/go/bin $path)
[[ -d ~/.cargo/env ]] && . "$HOME/.cargo/env"

[[ -d ~/.zsh/fpath ]] && fpath=($fpath ~/.zsh/fpath)
