HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS

unsetopt BEEP

bindkey -v
KEYTIMEOUT=1

export EDITOR=vim

ps -ef | grep -q '[s]sh-agent' || eval `ssh-agent` >/dev/null
which rbenv  >/dev/null && eval "$(rbenv init -)"
which nodenv >/dev/null && eval "$(nodenv init -)"
which dip >/dev/null && eval "$(dip console)"

autoload_inits=(compinit)
for f in $autoload_inits; do
  autoload -Uz $f && $f
done

source ~/.zsh/aliases
source ~/.zsh/functions
{%@@ if work @@%}
source ~/.zsh/zsh.work
{%@@ endif @@%}

zstyle ':completion:*' menu select

source ~/.zsh/powerlevel10k/powerlevel10k.zsh-theme
source ~/.zsh/purepower
source ~/.zsh/fsh/fast-syntax-highlighting.plugin.zsh
