#!/bin/bash

if [[ `uname` = 'Darwin' ]]; then
  brew bundle
fi

git submodule init
git submodule update --recursive
pip3 install -r dotdrop/requirements.txt --user
./dotdrop/bootstrap.sh

if [[ "$CODESPACES" -eq "true" ]]; then
  ./dotdrop.sh install -p codespaces --force
fi
