#!/bin/bash

git submodule update --recursive
pip3 install -r dotdrop/requirements.txt --user
./dotdrop/bootstrap.sh

if [[ `uname` = 'Darwin' ]]; then
  brew bundle
fi

if [[ "$CODESPACES" -eq "true" ]]; then
  ./dotdrop.sh install -p codespaces
fi
