shopt -s histappend
HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# start ssh-agent if it's not running
ps -ef | grep -q '[s]sh-agent' || eval $(ssh-agent) >/dev/null


[ -f ~/bin ] && export PATH=${PATH}:~/bin
[ -d /Applications/Postgres.app/Contents/Versions/latest/bin ] && export PATH=${PATH}:/Applications/Postgres.app/Contents/Versions/latest/bin

if [ -d ~/projects/google-cloud-sdk ]; then
  . ~/projects/google-cloud-sdk/path.bash.inc
  . ~/projects/google-cloud-sdk/completion.bash.inc
fi

export EDITOR=vim

HISTSIZE=10000000
HISTFILESIZE=10000000000000
export PROMPT_COMMAND="history -a; history -n;"

# git completion
[ -f /usr/share/git/completion/git-prompt.sh ] && . /usr/share/git/completion/git-prompt.sh
[ -f /usr/share/git/completion/git-completion.bash ] && . /usr/share/git/completion/git-completion.bash
[ -f /etc/bash_completion.d/git-prompt ] && . /etc/bash_completion.d/git-prompt

[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
[ -f /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
[ -f /etc/bash_completion ] && . /etc/bash_completion

[ -f ~/.bash_aliases ] && . ~/.bash_aliases
{%@@ if not work @@%}
[ -f /usr/local/opt/rbenv/shims ] && export PATH=$PATH:/usr/local/opt/rbenv/shims
type -t rbenv >/dev/null && eval "$(rbenv init -)"
{%@@ endif @@%}
type -t nodenv >/dev/null && eval "$(nodenv init -)"

[[ -f "~/.cargo/env" ]] && . "$HOME/.cargo/env"

eval "$(starship init bash)"
{%@@ if work @@%}

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)

# cloudplatform: add Shopify clusters to your local kubernetes config
export KUBECONFIG=${KUBECONFIG:+$KUBECONFIG:}/Users/ahayworth/.kube/config:/Users/ahayworth/.kube/config.shopify.cloudplatform
{%@@ endif @@%}
